### ISSUE TITLE
Can't activate the cddd conda env

### ISSUE THREAD

**Issue by rajarshi** [jrwnter/cddd#2]
Following the instructions on setting up a CPU environment on OS X, I am unable to activate the `cddd` env that I created.

```
20:23 $ source activate cddd

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 98, in main
        return activator_main()
      File "/anaconda3/lib/python3.6/site-packages/conda/activate.py", line 632, in main
        print(activator.execute(), end='')
    UnicodeEncodeError: 'ascii' codec can't encode character '\u2718' in position 26: ordinal not in range(128)
```
This is on OS X 10.12.6, Python 3.6.5 and conda 4.5.11

**Comment by jrwnter** [comment]
Sorry for responding tso late, but this seems to be an issue related to your anacoda setup (calling activate).
