### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by zchwang** [jrwnter/cddd#31]
Hi,

I encountered the following error while generating molecular embeddings (using "cddd --input smiles.smi --output descriptors.csv  --smiles_header smiles") from SMILES input. The occurrence of this error is approximately 20%. Is there any way to avoid this error?

"""
Consider installing the package zmq to utilize the InferenceServer class
start preprocessing SMILES...
finished preprocessing SMILES!
start calculating descriptors...
I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Error: seq2emb
Traceback (most recent call last):
  File "/home/wzc/anaconda3/envs/cddd/bin/cddd", line 8, in <module>
    sys.exit(main_wrapper())
  File "/home/wzc/anaconda3/envs/cddd/lib/python3.6/site-packages/cddd/run_cddd.py", line 99, in main_wrapper
    tf.app.run(main=main, argv=[sys.argv[0]] + UNPARSED)
  File "/home/wzc/anaconda3/envs/cddd/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/wzc/anaconda3/envs/cddd/lib/python3.6/site-packages/cddd/run_cddd.py", line 80, in main
    descriptors = infer_model.seq_to_emb(sml_list)
  File "/home/wzc/anaconda3/envs/cddd/lib/python3.6/site-packages/cddd/inference.py", line 127, in seq_to_emb
    emb = sequence2embedding(self.encode_model, self.hparams, seq)
  File "/home/wzc/anaconda3/envs/cddd/lib/python3.6/site-packages/cddd/inference.py", line 46, in sequence2embedding
    embedding_array = np.concatenate(emb_list)
ValueError: need at least one array to concatenate
"""

Best regards.

**Comment by jrwnter** [comment]
Hi, this looks like the model is not returning a single representation in emb_list. My guess is that either the smiles contain only characters that are ignored by the model or the preprocessing removes all the smiles...
Can you try running this with the "--no-preprocess" flag?

**Comment by Jalil-Mahdizadeh** [comment]
Hi,
@jrwnter does using --no-preprocess means no need for rdkit?
